language: c
 
install:
 - sudo apt-get install mono-devel mono-gmcs nunit-console
    
script:
 - EnableNuGetPackageRestore=true xbuild Algolia.Search/Algolia.Search.csproj 
 - EnableNuGetPackageRestore=true xbuild Algolia.Search.Test/Algolia.Search.Test.csproj 
